### ISSUE TITLE
请教Grafana调整Panel的Title字体大小的问题

### ISSUE THREAD

**Issue by kiic-leung** [YHYJ/MyBlogs#1]
请问能否附上里面的截图呢？感谢

**Comment by YHYJ** [comment]
[这个文件](https://github.com/YHYJ/MyBlogs/blob/main/content/post/Grafana调整Panel的Title字体大小.md)里有图片链接啊，存在gitee上，看不了么？

**Comment by kiic-leung** [comment]
> [这个文件](https://github.com/YHYJ/MyBlogs/blob/main/content/post/Grafana%E8%B0%83%E6%95%B4Panel%E7%9A%84Title%E5%AD%97%E4%BD%93%E5%A4%A7%E5%B0%8F.md)里有图片链接啊，存在gitee上，看不了么？

只显示了gitee图标噢，可能是我打开方式不对？

**Comment by YHYJ** [comment]
[grafana.zip](https://github.com/YHYJ/MyBlogs/files/9928055/grafana.zip)
